# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8cbdf148e280421fd349fd37a5d0a4acb4be61513c0996d232dbad64573bf63ef7d2da0e796ef7e5e773dc290b8058d3708d82de9c36ef04bda12fc171cbdb

test:
  secret_key_base: 23079fade78a2cf4003e602fe20de157d660787856a79a895592a2a1251ccd0bbb58c20f1f9a6c43fcac4f5cd751b77bac0209bcc53723f08a956a6105085cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
